daemon: false

log:
    displayLevel: 1
    fileLevel: 0
    useSyslog: false
    filePath: .
    activityFilePath: .
    fileRoot: DVMCC

network:
    enable: true
    id: xxx
    address: 10.147.147.245
    port: 63030
    password: "xxx"

    encrypted: false

    jitter: 360

    slot1: true
    slot2: true

    updateLookups: true
    saveLookups: true
    allowActivityTransfer: true
    allowDiagnosticTransfer: true
    allowStatusTransfer: true

    debug: false

    restEnable: true
    restAddress: xxx
    restPort: 9990
    restSsl: false
    restPassword: "xxx"
    restDebug: false

protocols:
    dmr:
        enable: false

    p25:
        enable: true
        tduPreambleCount: 6

        control:
            enable: true
            ackRequests: true
            dedicated: true
            broadcast: true
            interval: 300
            duration: 1
            disableTSDUMBF: false
            enableTimeDateAnn: true
            disableGrantSourceIdCheck: false
            redundantImmediate: true
            redundantGrantTransmit: true

        controlOnly: true
        disableNetworkHDU: false
        disableNetworkGrant: false
        inhibitUnauthorized: false
        legacyGroupGrnt: false
        legacyGroupReg: false
        convNetGrantDemand: false
        verifyAff: false
        verifyReg: false
        disableUnitRegTimeout: false
        requireLLAForReg: false
        dumpDataPacket: false
        repeatDataPacket: true
        dumpTsbkData: false
        callHang: 5
        noStatusAck: false
        noMessageAck: true
        unitToUnitAvailCheck: false
        allowExplicitSourceId: true
        sndcpGrant: false
        silenceThreshold: 124
        frameLossThreshold: 6
        queueSize: 12
        verbose: true
        debug: false

    nxdn:
        enable: false

system:
    identity: 1-xx-CC
    timeout: 180
    duplex: true
    simplexSameFrequency: false
    modeHang: 10
    fixedMode: true
    rfTalkgroupHang: 10
    activeTickDelay: 5
    idleTickDelay: 5
    localTimeOffset: 0

    info:
        latitude: 30.2991079
        longitude: -97.6917385
        height: 1
        power: 1
        location: "Austin, Texas"

    config:
        authoritative: true
        supervisor: true

        channelId: xxx
        channelNo: xxx

        voiceChNo:
            - channelId: xxx
              channelNo: xxx
              restAddress: xxx
              restPort: 9990
              restPassword: "xxx"
              restSsl: false

        secure:
            key: "000102030405060708090A0B0C0D0E0F"

        nac: 293

        pSuperGroup: 2321
        announcementGroup: 50

        netId: DEE00
        sysId: 13B
        rfssId: 1
        siteId: xxx

    cwId:
        enable: true
        time: 15
        callsign: WRUP970

    modem:
        protocol:
            type: "uart"

            uart:
                port: /dev/ttyAMA0
                speed: 115200

        rxInvert: false
        txInvert: false
        pttInvert: false
        dcBlocker: true
        cosLockout: false
        fdmaPreamble: 80
        p25CorrCount: 8
        p25FifoLength: 522

        hotspot:
            p25DiscBWAdj: 0
            p25PostBWAdj: 0
            adfGainMode: 2
            afcEnable: true
            afcKI: 13
            afcKP: 5
            afcRange: 1
            txTuning: 0
            rxTuning: 0

        repeater:
            p25SymLvl3Adj: 0
            p25SymLvl1Adj: 0

        softpot:
            rxCoarse: 127
            rxFine: 127
            txCoarse: 127
            txFine: 127
            rssiCoarse: 127
            rssiFine: 127

        rxDCOffset: 0
        txDCOffset: 0
        rxLevel: 50
        txLevel: 50
        rssiMappingFile: RSSI.dat
        packetPlayoutTime: 10
        disableOFlowReset: false
        ignoreModemConfigArea: false
        dumpModemStatus: false
        trace: false
        debug: false

    iden_table:
        file: /opt/centrunk/configs/iden_table.dat
        time: 30

    radio_id:
        file: /opt/centrunk/configs/rid_acl.dat
        time: 2
        acl: false

    talkgroup_id:
        file: /opt/centrunk/configs/talkgroup_rules.yml
        time: 2
        acl: false
